export enum ApiEndpoints {
    SIGNUP = '/auth/signup',
    UPLOAD_FILE = '/file/upload',
    RECOMMEND_RECIPE = '/recipe/recommend',
    LOGIN = '/auth/login',
    FORGOT_PASSWORD = '/auth/forgot-password',
    VERIFY_OTP = '/auth/verify-otp',
    RESET_PASSWORD = '/auth/reset-password',
    REFRESH_TOKEN = '/auth/refresh',
    CHECK_AUTH_TOKEN = '/auth/check-auth',
    RECIPES = '/recipe',
    CATEGORY = '/category',
    RECIPES_CATEGORY = 'recipe/category',
    MEASURE_UNIT = '/measure-units',
}
