export enum EndpointNames {
    DRAFT = 'draft',
    BLOGS = 'blogs',
    BLOG_ID = 'blogId',
    AUTH_TOKEN = 'authToke',
    FILE = 'file',
    USER_ACTIONS = 'userActions',
    LOGIN = 'login',
    FORGOT_PASSWORD = 'forgotPassword',
    VERIFY_OTP = 'verifyOtp',
    RESET_PASSWORD = 'resetPassword',
    POST_AUTH = 'postAuth',
    GET_RECIPES = 'getRecipes',
    GET_CATEGORY = 'getCategory',
    RECIPE_BLOGS = 'recipeBlogs',
    MEASURE_UNIT = 'measureUnit',
}
